### ISSUE TITLE
無限スクロールで更新された画像へのマウスホバーアニメーションが機能しない件

### ISSUE THREAD

**Issue by yohey222** [yohey222/my_portfolio#36]
### 画像の一覧ページにて
- jscroll機能を用いて無限スクロールを実装させている
- jqueryのマウスホバー機能で、画像にマウスホバーした時、画像の情報が表示される機能を実装させている
### 問題点
jscrollで更新された画像にもマウスホバーアニメーションを実行させたいが、機能しない。

※上半分がjscroll更新前の画像たち、下半分が更新後の画像たち
![d29p8-n7pc4 (1)](https://user-images.githubusercontent.com/61341624/83503810-9e238d80-a4fe-11ea-9fc9-395baed2694b.gif)

### 試したこと
- スクロール更新した時にマウスホバーのスクリプトが読み込めていないものだと思い、そのスクリプトを、更新するページのhtml内に記述したがうまくいかなかった。
- ".item-info" のscssの初期値をvisibility: hidden;にし、jqueryでスタイルをvisibility: visible;に変化するよう指定してみたが結果は同じだった

### ソースコード
HTML
```ruby
<div class="jscroll">
	<div class="photo-list">
		<% photos.each do |photo| %>
			<%= link_to photo_path(photo) do %>
				<div class="photo-list-item">
					<%= attachment_image_tag photo, :image %>
					<span class="item-info"><p><%= photo.address %></p></span>
				</div>
			<% end %>
		<% end %>
		<%= paginate photos %>
	</div>
</div>
```
SCSS
```scss
.photo-list-item {
	position: relative;
	margin-bottom: 20px;
	.attachment {
		display: block;
		// 親要素の高さをattachmentに合わせる

		width: 100%;
	}
	.item-info {
		display: none;
		position: absolute;
		top: 0;

		width: 100%;
		height: 100%;
		background: linear-gradient(to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0));
		p {
			padding: 5px;
			color: $light;
		}
	}
}
```
JS
```javascript
$(document).on('turbolinks:load', function() {

	// TOP
	// 投稿画像 無限スクロール
	$('.jscroll').jscroll({
		// 更新する要素
		contentSelector: '.jscroll',
		// 更新するリンク
		nextSelector: 'span.next a'
	});

	// 投稿画像 マウスホバーによる動き
	$('.photo-list-item').hover(function() {
			$('.item-info', this).show();
	}, function() {
			$('.item-info', this).hide();
	});
});
```

**Comment by yohey222** [comment]
以下の記述で解消
※classや要素の入れ子関係を整理済み

```javascript
// javascripts/application.js
	// 投稿画像 マウスホバーアニメーション
	// jscrollで更新後、hoverが発火しないのでこの記述
	$(document).on('mouseenter','.photo',function(){
	  $('.photo-info', this).show();
	});
   $(document).on('mouseleave','.photo',function(){
	  $('.photo-info', this).hide();
	});
```
第一引数をdocumentに、第二引数をphotoに、mouseenter、mouseleaveで更新後の画像にも発火
→[デモサイトトップページ](http://54.168.198.245/photos)

```html.erb
<!-- photos/_photos.html.erb -->
<div class="photos">
	<% photos.each do |photo| %>
		<%= link_to photo_path(photo), class: 'photo' do %>
			<%= attachment_image_tag photo, :image %>
			<p class="photo-info"><%= photo.address %></p>
		<% end %>
		<% if admin_signed_in? %>
			<%= link_to "削除", photo_path(photo), method: :delete, data: { confirm: "削除しますか？" } %>
		<% end %>
	<% end %>
	<%= paginate photos %>
</div>
```
```scss
// application.scss
.photos {
	margin-top: 30px;
	column-count: 3;
	.photo {
		position: relative;
		margin-bottom: 20px;
		display: block;
		.attachment {
			width: 100%;
			display: block;
			// 親要素の高さをattachmentに合わせる
		}
		.photo-info {
		// .photo-list-itemへのmouseHoverで表示
			display: none;
			position: absolute;
			top: 0;
			width: 100%;
			height: 100%;
			background: linear-gradient(to bottom, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0));
			padding: 5px;
			color: $light;
		}
	}
	.pagination {
		display: none;
	}
}
// 投稿一覧テンプレート
```
